version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isolation-forest-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ${PWD}:/app
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - anomaly-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
        - anomaly-network

volumes:
  redis_data:

networks:
  anomaly-network:
    external: true